"""add cancel to Rescue

Revision ID: 023a9791b227
Revises: 1fe39a4f2a0e
Create Date: 2020-02-20 16:06:35.054513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023a9791b227'
down_revision = '1fe39a4f2a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rescue', sa.Column('cancel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rescue', 'cancel')
    # ### end Alembic commands ###
