"""add cancel to SeekHelp

Revision ID: 1fe39a4f2a0e
Revises: 
Create Date: 2020-02-20 15:22:18.932622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe39a4f2a0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seek_help', sa.Column('cancel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seek_help', 'cancel')
    # ### end Alembic commands ###
